### ISSUE TITLE
Focos duplicados na síntese

### ISSUE THREAD

**Issue by MarceloPilatti** [TerraMA2/terrama2-report#238]
Verificar porque os focos da síntese estão aparecendo duplicados nas imagens e no valor que existe na descrição delas

**Comment by guianderson** [comment]
Realizadas as devidas consultas, verificado que varios pontos se repetem diversas vezes ao longo dos dias.

![](https://cdn.discordapp.com/attachments/689804770306818121/778622699475959848/unknown.png)

![](https://cdn.discordapp.com/attachments/689804770306818121/778618869190492191/unknown.png)
